Add Tooltip to mailcow Apps
mailcow/mailcow-dockerized pull request #347
Opened 2017-06-11 00:18 UTC by PhoenixPeca

Basically, this allows the admin to set an optional custom description of a specific mailcow app that can be read on mouse hover. Additionally, I have also added `htmlspecialchars` to escape double quotes in some html attributes. The descriptions are in english by default, but users can always customize them in `vars.local.inc.php` so I don't think we'll need a dedicated translation entries in the `lang` folder.
![sdgdfg](https://user-images.githubusercontent.com/9730242/27007206-26baf060-4e7d-11e7-901b-a9fdcba36222.jpg)

2017-06-11 16:08 UTC, mkuron requested changes

2017-06-11 16:08 UTC, mkuron commented on data/web/inc/vars.inc.php
> +    'description' => 'SOGo is a collaborative software (groupware) server.'
Change the descriptions to something less technical, e.g. "Web access to your email, contacts and calendar" and "Web access to your email".

2017-06-11 22:12 UTC, PhoenixPeca commented on data/web/inc/vars.inc.php
> +    'description' => 'SOGo is a collaborative software (groupware) server.'
@mkuron how about this one "SOGo is a multi-purpose groupware server that provides native Microsoft ActiveSync support."? 😄

2017-06-12 05:29 UTC, mkuron commented on data/web/inc/vars.inc.php
> +    'description' => 'SOGo is a collaborative software (groupware) server.'
Remember, this page is used by the end user, not that much by the admin. They might never have even heard about "groupware" or "ActiveSync". Also, ActiveSync is not used in the browser through the link here, so it doesn't need to be mentioned in the description.

2017-06-12 05:41 UTC, PhoenixPeca commented on data/web/inc/vars.inc.php
> +    'description' => 'SOGo is a collaborative software (groupware) server.'
Any suggestions? 😄

2017-06-12 05:49 UTC, PhoenixPeca commented on data/web/inc/vars.inc.php
> +    'description' => 'SOGo is a collaborative software (groupware) server.'
"SOGo is a web-based client for email, address book and calendar."
"Roundcube is a light-weight substitute of SOGo webmail."

2017-06-12 06:16 UTC, mkuron commented on data/web/inc/vars.inc.php
> +    'description' => 'SOGo is a collaborative software (groupware) server.'
The first one is good. Change the second one to "Roundcube is a web-based email client" (i.e. drop the SOGo reference and don't claim it's lightweight -- it's a pretty massive piece of PHP and JS after all).

2017-06-12 07:41 UTC, merged