Add comment about maildir_very_dirty_syncs to dovecot.conf
mailcow/mailcow-dockerized pull request #4028
Opened 2021-03-13 18:49 UTC by Daniel15

`maildir_very_dirty_syncs` can significantly improve performance of very large mailboxes. 

From Roundcube's logs when loading one email from a mailbox containing 250k emails:
Before: 1.719s to fetch:
```
A0008 OK Fetch completed (0.860 + 0.000 + 0.859 secs).
```

After: 0.025s to fetch:
```
A0008 OK Fetch completed (0.013 + 0.000 + 0.012 secs).
```

What this option does is it avoids rescanning the entire `cur` directory whenever loading an email. With this option disabled, Dovecot takes it safe and scans the ENTIRE `cur` directory (essentially running an `ls`) to check if that particular email was touched (renamed, etc). This is very slow if the directory is large, even on filesystems optimized for such use cases (eg. ext4 with dir_index enabled). 

With this option enabled, Dovecot will still notice changes if the file's mtime is changed, but otherwise it will not scan the directory and just assumes the index is up-to-date. This is essentially the same as what sdbox/mdbox do, and with this option you can get some of the performance increase that would come with sdbox/mdbox (see #1007) while still using maildir.

This is safe to use as long as you do not manually touch files under `cur` (as then Dovecot may not notice the changes). Delivering new emails using LMTP (which Mailcow does) is fine, and dropping new emails into the `new` directory is also fine, it's just modifying stuff under `cur` that's a bit risky.

This option seems to be safe to enable with Mailcow, as nothing appears to directly modify files in the `cur` directory other than Dovecot (Docker is very useful to verify this - the volume is not mounted in any other Docker containers). Some other systems enable it default - For example, cPanel has it enabled by default.

2021-04-25 07:10 UTC, andryyy commented
I thought about adding this as default a while ago. What do you guys think?

2021-04-25 07:13 UTC, Daniel15 commented
@andryyy  I'd be fine with it being the default. cPanel has it enabled by default so the risk should be fairly minimal. A standard Mailcow installation would have no problems with this setting being enabled - It's only if people manually modify the maildir files (which is pretty rare) that there'd be any problems. This could just be documented in the Mailcow docs though.

2021-04-25 07:31 UTC, andryyy commented
Yes, should be in the docs indeed. :)

2021-05-01 20:35 UTC, andryyy commented
Still testing it, it feels good.

Can you create a PR for the docs? Only if you like and find time. If you don't, I will do it.

2021-05-01 20:39 UTC, Daniel15 commented
Sure, I'll send a PR when I get a chance.

2021-05-02 23:39 UTC, Daniel15 commented
I updated this PR to actually enable the option rather than just adding a comment, and created a PR for the docs site (https://github.com/mailcow/mailcow-dockerized-docs/pull/275) to add some docs :)

2021-05-04 11:57 UTC, sschwetz commented
The only reason that I could see to not enable this by default would be that I it doesn't place nice with NFS. But I don't see this as being a major issue as many other portions of mailcow (mariadb) do not work at all when stored on NFS.

2021-05-04 16:59 UTC, Daniel15 commented
> The only reason that I could see to not enable this by default would be that I it doesn't place nice with NFS.

@sschwetz  It's actually fine over NFS as long as you follow the rule that nothing other than Dovecot should touch the maildir files. In particular, running multiple Dovecot instances that use the same maildir, like you might with a high-availability configuration, may not work properly. I wouldn't expect most Mailcow users to want to do that though. I've also seen some posts on their mailing list that say it's actually fine as long as the Dovecot instances also share the same index, but I'm not sure how well that works in terms of locking.

2021-07-11 00:45 UTC, Daniel15 commented
@andryyy Could you please consider merging this? The bot closed it :(

2021-07-30 22:48 UTC, patschi commented
I like the change and I think it might be beneficial performance-wise indeed. However wondering, if dovecot doesn't scan the whole `cur/` folder each time, is there a way forcing dovecot to rescan if manual changes were done? (I guess restarting dovecot should do the trick?) There might be users doing changes in the folder, so we should at least provide a comment how to force a rescan if required.

@andryyy You've been testing this one since quite a while. Assuming you haven't seen any issues, I think it might be ready to merge.

However we might want to note somewhere that manually manipulating files in `cur/` isn't something we recommend/support?

2021-07-30 22:52 UTC, Daniel15 commented
> if dovecot doesn't scan the whole cur/ folder each time, is there a way forcing dovecot to rescan if manual changes were done?

You need to shut down Dovecot, delete the relevant indexes for the folder that was modified (in `vmail-index-vol-1`), and then start Dovecot again. It'll rebuild the indexes on the fly as needed.

Having said that, I don't think people would be manually modifying the maildir files for a Mailcow instance very often, given they're encrypted so you can't just open them in a regular text editor and modify them.

2021-07-30 23:08 UTC, patschi commented
Makes sense. IMHO it might be good to add a quick side-note to the DocPR of yours, just for completeness.

I'm adding the option on my installations, let's see how it works out.

2021-07-30 23:09 UTC, Daniel15 commented
Sure, I'll do that when I get a chance.

For what it's worth, I've been using this option on my mailserver since the start of the year and haven't hit any issues with it 😄

2021-07-30 23:12 UTC, patschi commented
Sure, take your time.

Just one more thing, to be picky, changing:
```
maildir_very_dirty_syncs=yes
```
to
```
maildir_very_dirty_syncs = yes
```
(with spaces, just like the other settings)

2022-03-02 00:20 UTC, Ry3nlNaToR commented
Hi, Just wondering is there any plans to merging this, enabling maildir_very_dirty_syncs shouldn't break anyone server, the only case where this would be issue if someone was doing manual edits in the maildir for 99.9% of users that would very unlikely since the files in maildir are lz4 compressed and encrypted.

Enabling it significantly speeds up imap fetch especially helpful for users with large inboxes.

2022-09-24 14:29 UTC, ricardoamaro commented
Plus one for getting this merged, please! :)

2022-09-24 20:01 UTC, DerLinkman commented
Will look into it.

2022-11-21 18:52 UTC, dasn4pp3l commented
+1 for merge

2023-05-03 09:35 UTC, Turab commented
Would this improve things with SoGO too? Or we have to use only Roundcube?

2023-05-03 09:38 UTC, ghost commented
> Would this improve things with SoGO too? Or we have to use only Roundcube?

Any email client would benefit from this.

2023-05-03 10:25 UTC, DerLinkman requested changes
Only that small change, the rest looks good!

Many thanks

2023-05-03 10:25 UTC, DerLinkman commented on data/conf/dovecot/dovecot.conf
> +# https://mailcow.github.io/mailcow-dockerized-docs/u_e-dovecot-perf/
Please change the docs link to: https://mailcow.github.io/mailcow-dockerized-docs//manual-guides/Dovecot/u_e-dovecot-performance/

2023-05-03 13:14 UTC, MAGICCC commented on data/conf/dovecot/dovecot.conf
> +# https://mailcow.github.io/mailcow-dockerized-docs/u_e-dovecot-perf/
You mean https://docs.mailcow.email/manual-guides/Dovecot/u_e-dovecot-performance/ for the domain?

2023-05-03 13:15 UTC, DerLinkman commented on data/conf/dovecot/dovecot.conf
> +# https://mailcow.github.io/mailcow-dockerized-docs/u_e-dovecot-perf/
Ah yes sorry....

2023-05-24 08:53 UTC, DerLinkman approved these changes
Looks very good!

I'm doing some final tests and will merge it then.

2023-05-24 09:00 UTC, merged