[Dovecot/FTS] Replace Xapian with Solr
mailcow/mailcow-dockerized pull request #4456
Opened 2022-02-07 07:41 UTC by DerLinkman

### DO NOT MERGE UNTIL ALL CHECKS ARE MADE

**This PR replaces Solr FTS with Xapian FTS**

It is usable but not nearly finished!

What is done? What needs to be added?:

- [X] Dovecot Update + Xapian compilation
- [X] Xapian variable replacement from mailcow.conf and docker-compose.yml
- [X] Xapian Replacement in generate-config.sh & update.sh
- [X] Addition of new extra config file to control the Xapian Plugin
- [ ] Change of the Dovecot Index Folder/Structure to be more granually
- [ ] Addition of new Docker Volume (xapian-index-vol) in docker-compose.yml
- [ ] Addition of Dovecot Index Cleanup Cronjob? When a mailbox is deleted no Indexes will be deleted (by now)
- [ ] Xapian Replacement in WebUI
- [ ] (Not decided yet) Add new Reindex Dovecot Indexes Button in WebUI (Xapian section)
- [ ]  Solr API removal (Xapian replacement?)
- [ ] Final Tests

2022-02-07 16:56 UTC, MAGICCC commented
Nice! We could convert the PR into a draft so we won't delete it accidentally :D 

Also we need to redo the translation parts (renaming Solr to Xapian)
What about old installations and their configs? Do you plan to try to remove the corresponding lines from the mailcow.conf?
E.g.
https://github.com/mailcow/mailcow-dockerized/blob/master/generate_config.sh#L250-L257

2022-02-07 17:09 UTC, DerLinkman commented
Why do we need to remove the Xapian translation? It is replacing the solr. I didn't tested it until now. New mailcow Installations works flawlessly

2022-02-07 20:49 UTC, mkuron requested changes
Could you please provide some rough numbers how much memory and disk space Xapian and Solr take up for an "average" user‘s mailbox, e.g. 10000 messages? Xapian should be better than Solr, but we should know by how much.

2022-02-07 20:49 UTC, mkuron commented on data/Dockerfiles/dovecot/Dockerfile
> +  sudo \
You shouldn’t need sudo in the Dockerfile, it all runs as root.

2022-02-07 20:49 UTC, mkuron commented on data/Dockerfiles/dovecot/Dockerfile
> +  && rm -rf /tmp/* /var/tmp/* /root/.cache/
You need to merge everything into a single `RUN` command, otherwise this cleanup won‘t help shrink the image size.

2022-02-07 20:49 UTC, mkuron commented on data/Dockerfiles/dovecot/decode2text.sh
> +# }
I would suggest to drop the attachment extraction script. We didn‘t have attachment indexing enabled with Solr either and I don’t think we have the necessary packages installed in this image for PDF or doc/xls/ppt support. Attachments also tend to be much larger than the email message themselves and indexing would thus increase the xapian database size significatnly.

2022-02-23 15:22 UTC, DerLinkman commented
> Could you please provide some rough numbers how much memory and disk space Xapian and Solr take up for an "average" user‘s mailbox, e.g. 10000 messages? Xapian should be better than Solr, but we should know by how much.

### Test Results (Default Xapian config)

**Cons:**
- Xapian is slower than solr (5 mins min)
- needs more space on disk (100% min)
- Dovecot Image is larger than without Xapian (needs to be compiled)

**Pros:**
- No Java!
- Can run with 512MB Ram
- Quick query results (650 Values in 14ms)
- Indexes are not single files (these are Databases so to say)
- Build in Dovecot, no extra container needed

2022-02-23 18:16 UTC, mkuron commented
Those numbers sound pretty good.

> needs more space on disk (100% min)

Disk space is cheap (a lot cheaper than RAM), so that's a tradeoff probably anyone would be willing to make.

> Xapian is slower than solr (5 mins min)

The time the initial indexing takes is pretty much irrelevant because it's a one-time cost. On-the-fly indexing of new messages will take negligible time.

> Quick query results (650 Values in 14ms)

14ms seems like an absolutely acceptable query time, though I don't know how fast SOLR is.

2022-07-19 05:46 UTC, andryyy commented
As long as this is just to play around, it’s fine. Don’t ever merge this to master, please, before several things are fixed and there is an official release.

2023-01-18 09:20 UTC, VermiumSifell commented
I think the issue title should be named Replace Solr with Xapian, as I currently understands the title as going from Xapian to Solr

2023-01-18 11:15 UTC, DerLinkman commented
> I think the issue title should be named Replace Solr with Xapian, as I currently understands the title as going from Xapian to Solr

Absolutely right. Don't know if i was drunk or something why that happend :)

Thanks anyways

2024-01-30 10:37 UTC, closed without merging

2024-01-30 14:19 UTC, jpbaril commented
Feature abandoned?

2024-01-30 14:28 UTC, DerLinkman commented
No just redone with the current mailcow development branches (see: https://github.com/mailcow/mailcow-dockerized/tree/feat/fts-flatcurve)