Watchdog: Allow sending notifications via webhooks
mailcow/mailcow-dockerized pull request #4968
Opened 2023-01-07 15:32 UTC by felixoi

Inspired by #3672 and #4198 this adds a way to send watchdog notifications to any JSON-compilant webhook service.

2023-01-08 18:53 UTC, felixoi commented
In addition to this PR, I'm thinking about adding support for the health status webhook of every service monitored by watchdog (to use services like healthchecks.io). This would result in a lot of new config variables. Not sure how to handle this.

2023-01-08 18:59 UTC, MAGICCC requested changes

2023-01-08 18:59 UTC, MAGICCC commented on update.sh
> +      echo '#WATCHDOG_NOTIFY_WEBHOOK_BODY=\'{"username": "Mailcow Watchdog", "content": "**${SUBJECT}**\n${BODY}"}\'' >> mailcow.conf
It's mailcow not Mailcow

2023-01-08 18:59 UTC, MAGICCC commented on generate_config.sh
> +#WATCHDOG_NOTIFY_WEBHOOK_BODY='{"username": "Mailcow Watchdog", "content": "**${SUBJECT}**\n${BODY}"}'
It's mailcow not Mailcow

2023-01-08 19:57 UTC, felixoi commented
@MAGICCC fixed.

2023-02-20 18:26 UTC, osos commented
may I suggest that somehow a differentiation in severity of the "error" is implemented and however for the hooks.

Maybe

- notify_error(subject, body)
- notify_warning(subject, body)
  - not sure which events are warnings
- notify_info(subject,body)
  - e.g. ip-ban

2023-02-20 18:42 UTC, felixoi commented
I've a lot things in mind that can be improved here like healthchecks (send a health ping ever x seconds a service is healthy and a fail ping to instantly fail), multiple webhooks for different services, ... I'd like to get the basic webhook in first and then improve this whole monitoring notification topic afterwards in multiple PRs.

2023-02-20 19:36 UTC, MAGICCC commented
Just tested a bit with the Pushover API and works fine:
![image](https://user-images.githubusercontent.com/3279213/220186672-f5270dde-d595-4ac1-afe7-890c56f216b6.png)




Does it makes sense to add a `WATCHDOG_WEBHOOK_VERBOSE` variable which adds a -v in the curl command?

You need to add in docker-compose the env vars in the watchdog image too:
```
        - WATCHDOG_NOTIFY_WEBHOOK=${WATCHDOG_NOTIFY_WEBHOOK}
        - WATCHDOG_NOTIFY_WEBHOOK_BODY=${WATCHDOG_NOTIFY_WEBHOOK_BODY}
```

2023-02-28 18:06 UTC, felixoi commented
Verbose option is pending because of #5081

2023-05-29 09:32 UTC, MAGICCC commented
Hi @felixoi are you still working on this?

2023-05-29 09:43 UTC, felixoi commented
@MAGICCC Yeah need to fix this up. When I started this I tried out mailcow and could just test this things on my Hetzner VM but now I'm using it in production so I can't test it there anymore. I may spin up a second instance for finishing this..

2023-05-29 14:45 UTC, MAGICCC commented
Nice to hear this!

2023-11-09 13:52 UTC, osos commented
how is this going?

a couple of times we had the postfix to crash. The watchdog could send me an email.

2023-11-09 14:02 UTC, felixoi commented
I'm really sorry that I haven't been able to finish this yet. My time is very limited at the moment and I would need to set up a new development environment. If anyone wants to finish this (I think just the verbose option is missing and tests if it works correctly if added), please feel free to do so.

2023-11-10 17:05 UTC, DerLinkman commented
No promise but we might finish it. But also for that: no eta just looking into things which are nice to have.

2023-11-10 17:08 UTC, MAGICCC commented
Maybe I have time at the weekend to finish this. As seen above it's already working, except a verbose option

2023-12-11 15:29 UTC, merged

2023-12-11 15:44 UTC, MAGICCC commented
Thanks @FreddleSpl0it for it. Didn't have time myself