enable search in bodies from EAS
mailcow/mailcow-dockerized pull request #5402
Opened 2023-09-02 09:35 UTC by cero1988

enable search in bodies from EAS

2023-09-04 19:34 UTC, MAGICCC requested changes

2023-09-04 19:34 UTC, MAGICCC commented on data/conf/sogo/sogo.conf
> +  SOGoEASSearchInBody = YES
```suggestion
  SOGoEASSearchInBody = YES;
```

2023-09-19 06:43 UTC, DerLinkman commented
Hi?

Could you please write at least your motivation or something else for this pr instead of : topic = discription?

Did you have tests for this or else?

2023-09-19 11:00 UTC, cero1988 commented
Hello,

I am testing this in my home mailcow server and It works.
I had configured my email via EAS protocol, and I needed to allow search even on message body.
Without this parameter, I could not search via EAS in message body, the only way for searching in messages bodies was to use webmail.
I think that this behaviour could be useful enabled by default.

2023-10-12 09:12 UTC, DerLinkman approved these changes
Looks fine!

2023-10-12 09:13 UTC, merged