Allow user skip unbound healthcheck
mailcow/mailcow-dockerized pull request #5652
Opened 2024-01-18 15:34 UTC by KagurazakaNyaa

Resolve #5651 #5649 

Suppress health checks for unbound container when you are in a bad/restricted network environment.
For example, the network in mainland China cannot connect to `github.com` normally, so the container health check always fails.

2024-01-18 15:35 UTC, milkmaker commented
Thanks for contributing!

I noticed that you didn't select `staging` as your base branch. Please change the base branch to `staging`.
See the attached picture on how to change the base branch to `staging`:

![check_prs_if_on_staging.png](https://raw.githubusercontent.com/mailcow/mailcow-dockerized/master/.github/workflows/assets/check_prs_if_on_staging.png)

2024-01-18 15:42 UTC, DerLinkman requested changes
Also is the Variable used inside the healthcheck missing at a docker compose variable for the unbound container

2024-01-18 15:42 UTC, DerLinkman commented on data/Dockerfiles/unbound/healthcheck.sh
> +if [[ "${SKIP_DNS_CHECK}" =~ ^([yY][eE][sS]|[yY])+$ ]]; then
Would call it SKIP_UNBOUND_HEALTHCHECK

2024-01-18 15:42 UTC, DerLinkman commented on data/Dockerfiles/unbound/healthcheck.sh
> +if [[ ${SKIP_DNS_CHECK} == "y" ]]; then
Would call it SKIP_UNBOUND_HEALTHCHECK

2024-01-18 15:42 UTC, DerLinkman commented on generate_config.sh
> +SKIP_DNS_CHECK=n
Would call it SKIP_UNBOUND_HEALTHCHECK

2024-01-18 15:42 UTC, DerLinkman commented on generate_config.sh
> +# Skip DNS check in Unbound container - y/n
Change to: Skip Unbound (DNS Resolver) Healthchecks (NOT Recommended!)

2024-01-18 16:00 UTC, DerLinkman requested changes
The Parameter will now only be set when you create a new mailcow. Old installations wouldn't get this in their mailcow.conf's.

Could you add it into the update.sh (like the previous parameters) as well?

2024-01-18 16:13 UTC, DerLinkman approved these changes
LGTM. I'll test the functionality and come back for a merge.

2024-01-18 18:08 UTC, MAGICCC commented
Maybe do it for all containers as a single var or multiple for each container?

2024-01-18 21:08 UTC, DerLinkman commented
Don't get this idea tbh.

2024-01-21 15:06 UTC, zenz commented
it doesn't work. I apply this path to local copy and start with docker composer, still cannot ignore the network checking and still fail to start other docker depend on unbound

2024-01-21 17:21 UTC, zenz commented
> it doesn't work. I apply this patch to local copy of container and restart it. it seems working. but when I login with admin user, always login failed.
> 
> Please fix this issue as soon as possible. my email server was down after this release 2024-01a.

OMG!, it seems this 2023-01a update removed all mysql data....

2024-01-22 08:56 UTC, DerLinkman commented
> > it doesn't work. I apply this patch to local copy of container and restart it. it seems working. but when I login with admin user, always login failed.
> > Please fix this issue as soon as possible. my email server was down after this release 2024-01a.
> 
> OMG!, it seems this 2023-01a update removed all mysql data....

This will not be answered here... as it has nothing to do with this PR. Head over to Telegram (https://t.me/mailcow) if you need help

2024-01-22 09:25 UTC, DerLinkman approved these changes
Merci! Looks good, works! Thanks

2024-01-22 09:25 UTC, merged

2024-01-22 17:16 UTC, Daniel15 commented
Wouldn't it be better to allow the domain it looks up to be customized, instead of totally disabling the health check?

2024-02-10 14:31 UTC, SnailShea commented
> Wouldn't it be better to allow the domain it looks up to be customized, instead of totally disabling the health check?

Not necessarily. It's entirely possible for network configuration to be set such that  the checked domain is reachable internally, and that does not guarantee that DNS works externally.

2024-09-10 19:54 UTC, karotu commented
I'm using 2024-08a on Ubuntu 24.04 minimized but still get this
`dependency failed to start: container mailcowdockerized-unbound-mailcow-1 is unhealthy
` 
error.

I have done
`docker compose stop`
`service docker restart`
`docker system prune -a`
and before starting, rechecked if 
`SKIP_UNBOUND_HEALTHCHECK=Y` still remains in mailcow.conf.

then did a
 
`docker compose up -d`

So it looks like it didn't skip the healthcheck?

On a tangent to dig deeper to this issue with healthcheck, I did a quick check in unbound shell to run ./healthcheck.sh which shows
`root@mail:/opt/mailcow-dockerized# docker compose exec unbound-mailcow /bin/bash
7740b7e4aeb7:/# ./healthcheck.sh 
2024-09-11 07:27:00: Healthcheck: DNS Resolution Failed on attempt 1 for fuzzy.mailcow.email! Trying again...
2024-09-11 07:27:02: Healthcheck: DNS Resolution Failed on attempt 2 for fuzzy.mailcow.email! Trying again...
2024-09-11 07:27:04: Healthcheck: DNS Resolution Failed on attempt 3 for fuzzy.mailcow.email! Trying again...
2024-09-11 07:27:04: Healthcheck: DNS Resolution not possible after 3 attempts for fuzzy.mailcow.email... Gave up!
2024-09-11 07:27:06: Healthcheck: DNS Resolution Failed on attempt 1 for github.com! Trying again...
2024-09-11 07:27:08: Healthcheck: DNS Resolution Failed on attempt 2 for github.com! Trying again...
2024-09-11 07:27:10: Healthcheck: DNS Resolution Failed on attempt 3 for github.com! Trying again...
2024-09-11 07:27:10: Healthcheck: DNS Resolution not possible after 3 attempts for github.com... Gave up!
2024-09-11 07:27:12: Healthcheck: DNS Resolution Failed on attempt 1 for hub.docker.com! Trying again...
2024-09-11 07:27:14: Healthcheck: DNS Resolution Failed on attempt 2 for hub.docker.com! Trying again...
^C
`
Did the extra checks while in unbound shell..
`7740b7e4aeb7:/# ping fuzzy.mailcow.email
PING fuzzy.mailcow.email (95.217.129.125): 56 data bytes
64 bytes from 95.217.129.125: seq=0 ttl=42 time=395.916 ms
64 bytes from 95.217.129.125: seq=1 ttl=42 time=400.014 ms
64 bytes from 95.217.129.125: seq=2 ttl=42 time=405.251 ms
^C
--- fuzzy.mailcow.email ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 395.916/400.393/405.251 ms
7740b7e4aeb7:/# dig +short +timeout=2 +tries=1 fuzzy.mailcow.email @127.0.0.1
;; communications error to 127.0.0.1#53: timed out
;; no servers could be reached
`
also did a dig within unbound shell to Google DNS and recheck fuzzy..
`7740b7e4aeb7:/# dig +short +timeout=2 +tries=1 fuzzy.mailcow.email @8.8.8.8
95.217.129.125
7740b7e4aeb7:/# dig +short +timeout=2 +tries=1 fuzzy.mailcow.email @127.0.0.1
;; communications error to 127.0.0.1#53: timed out
;; no servers could be reached`

Is 127.0.0.1 within unbound not serving DNS queries?
`7740b7e4aeb7:/# netstat -tulpn | grep :53
tcp        0      0 0.0.0.0:53              0.0.0.0:*               LISTEN      -
tcp        0      0 :::53                   :::*                    LISTEN      -
udp        0      0 0.0.0.0:53              0.0.0.0:*                           -
udp        0      0 :::53                   :::*   `

`7740b7e4aeb7:/# grep -E -w '53/(tcp|udp)' /etc/services
domain		53/tcp				# Domain Name Server
domain		53/udp
`

2024-09-10 20:43 UTC, karotu commented
My version: [2024-08a]
This is how I skipped the healthcheck.

**NOTE: This is only for a fresh install. Not an existing production server. If you have it in production, do your proper backups including your database credentials etc.

After cloning mailcow-dockerized into /opt, edit mailcow.conf and update the following line to
`SKIP_UNBOUND_HEALTHCHECK=Y`

**Do your backups if in Production!!**

If you have tried numerous times to get this up and running but with an unhealthy test, do the following:
stop the mailcow containers with `docker compose stop`
restart docker with `service docker restart` 
prune the system with `docker system prune -a`
then
`docker compose down --volumes`
This will remove your previous data and setup credentials so do your backups! This part always got me stuck as it seems it was still recalling settings from the existing volumes or something..

Now, do a 
`docker compose pull`
then 
`docker compose up -d`

This will hopefully get you past the healthcheck.

Thanks to the MailCow Team!

Happy Mailing.. MooHoo!