[Fix] Watchdog: escape subject and body for webhooks
mailcow/mailcow-dockerized pull request #5773
Opened 2024-03-01 22:15 UTC by mrclschstr

Proposal for escaping subject and body for webhooks, which fixes #5760. I tried to use a generic approach as mentioned [here](https://stackoverflow.com/a/2705678):

> As Ben Blank said, there are only three characters that need to be escaped in the replacement string (escapes themselves, forward slash for end of statement and & for replace all)

IP ban notifications using Pushover are now working for me:

![grafik](https://github.com/mailcow/mailcow-dockerized/assets/6423849/36dbf19b-8546-4e58-8c78-0b36523c7189)

2024-05-19 00:16 UTC, milkmaker commented
This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.

2024-05-19 05:53 UTC, mrclschstr commented
Bump, still relevant

2024-07-18 09:36 UTC, milkmaker commented
This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.

2024-07-18 10:05 UTC, mrclschstr commented
Bump, still relevant

2024-08-01 07:16 UTC, DerLinkman requested changes
Looks good. But we need a update in compose.yml too as we need to rebuild the container.

2024-08-01 08:12 UTC, mrclschstr commented
> Looks good. But we need a update in compose.yml too as we need to rebuild the container.

Sorry, I forgot about that. I'll add it later today.

2024-08-02 09:08 UTC, DerLinkman approved these changes
Looks fine to me :)

Will build the docker image upon merge (for next update 2024-08)

2024-08-07 12:48 UTC, merged