Allow hard-coding IPV4 and IPV6 rather than it being detected
mailcow/mailcow-dockerized pull request #5895
Opened 2024-06-05 18:53 UTC by cmer

This allows hardcoding `IPV4` and `IPV6` rather than being automatically detected when renewing SSL certificates.

This is handy in scenarios where outbound traffic comes from a different IP than what would normally be expected.

2024-06-05 18:54 UTC, milkmaker commented
Thanks for contributing!

I noticed that you didn't select `staging` as your base branch. Please change the base branch to `staging`.
See the attached picture on how to change the base branch to `staging`:

![check_prs_if_on_staging.png](https://raw.githubusercontent.com/mailcow/mailcow-dockerized/master/.github/workflows/assets/check_prs_if_on_staging.png)

2024-06-10 10:16 UTC, DerLinkman requested changes
Where does this IPs are set so the container can get them?

It needs at least a declaration inside the docker-compose.yml for the Static IPv4/IPv6 adress to be used as a variable inside the container...

2024-06-12 00:16 UTC, cmer commented
They are environment variables. If not set (this is the default), the IP is automatically resolved. Otherwise, if set, it uses the hardcoded IP in the environment variables.

2024-06-13 07:09 UTC, dragoangel commented
What is the purpose of this change? What are you trying to solve? If you using SNAT properly this should be never the case.

2024-10-06 18:45 UTC, milkmaker commented
This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.

2024-10-14 00:19 UTC, closed without merging