docker-compose: drop version declaration
mailcow/mailcow-dockerized pull request #5914
Opened 2024-06-19 11:09 UTC by kornrunner

Version is informative, not required. Newer versions of compose issue warnings if it's declared. 

Ref https://github.com/docker/compose/issues/11628

2024-06-19 11:09 UTC, milkmaker commented
Thanks for contributing!

I noticed that you didn't select `staging` as your base branch. Please change the base branch to `staging`.
See the attached picture on how to change the base branch to `staging`:

![check_prs_if_on_staging.png](https://raw.githubusercontent.com/mailcow/mailcow-dockerized/master/.github/workflows/assets/check_prs_if_on_staging.png)

2024-06-19 20:07 UTC, MAGICCC requested changes

2024-06-19 20:07 UTC, MAGICCC commented on docker-compose.yml
Already removed in https://github.com/mailcow/mailcow-dockerized/pull/5845

2024-06-19 20:07 UTC, MAGICCC commented on data/web/inc/lib/vendor/matthiasmullie/minify/docker-compose.yml
I wouldn't remove it from here, rather update this submodule

2024-06-19 20:17 UTC, kornrunner commented on data/web/inc/lib/vendor/matthiasmullie/minify/docker-compose.yml
I'll submit a new PR for that case, thanks

2024-06-24 07:04 UTC, DerLinkman commented
Duplicate, already merged in https://github.com/mailcow/mailcow-dockerized/commit/e0bde1c459bb4b5b8b21a67e0d98ac46b705f1bd

2024-06-24 07:04 UTC, closed without merging