Fix2752
mailcow/mailcow-dockerized pull request #6155
Opened 2024-11-12 06:08 UTC by PseudoResonance

## Contribution Guidelines

* [x] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree them

## What does this PR include?

### Short Description

Fix for #2752 to allow address rewriting to entire domains, instead of being limited to a single email.
I simply copied the old address validation code and replaced the new address validation so that they both share the same code.

###  Affected Containers

 - nginx

## Did you run tests?

### What did you tested?

I inputted a number of different valid/invalid domain and email combinations to ensure the validation works as intended.

### What were the final results? (Awaited, got)

Works as described in #2752 and either exact emails or whole domains can be added as a new address.

2025-01-15 13:33 UTC, milkmaker commented
This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.

2025-01-15 15:18 UTC, PseudoResonance commented
I rather dislike these stale bots...

2025-02-13 12:24 UTC, FreddleSpl0it requested changes
Please also apply this logic to `$new_dest`
```
      if (substr($old_dest, 0, 1) == '@') {
        $old_dest = substr($old_dest, 1);
      }
```

After adding a domain as `$new_dest`, an `@` is prepended. Editing this entry will only work if the `@` is removed.

2025-02-25 06:41 UTC, PseudoResonance commented
> After adding a domain as `$new_dest`, an `@` is prepended. Editing this entry will only work if the `@` is removed.

I think I implemented all of `old_dest`'s logic to `new_dest` as well. It now removes the prefixing `@` when editing it and properly handles it when included.

Additionally, I updated what localizations I could to indicate that an email or domain is valid. I simply used the old dest translation, and updated the new dest one to match. I checked them with Google translate and I believe I got all the grammar correct in the languages I could check, however I'm only fully confident about English, Japanese and Spanish. The rest I do not speak and just had to use the internet.

I can remove them though if you want them in another commit or something.

2025-02-26 08:59 UTC, FreddleSpl0it approved these changes

2025-02-26 09:01 UTC, merged