Add initial Japanese language files
mailcow/mailcow-dockerized pull request #6198
Opened 2024-12-04 13:10 UTC by kotaroman

## Contribution Guidelines

* [x] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree them

## What does this PR include?

### Short Description

This PR adds initial Japanese language support for mailcow by introducing translation files in `lang/ja`. It aims to provide better accessibility for Japanese-speaking users.

###  Affected Containers

- None (This PR affects only language files, not specific containers)

## Did you run tests?

### What did you tested?

- Verified that the Japanese language files load correctly in the application.
- Tested switching to Japanese and ensuring that translations are properly displayed.

### What were the final results? (Awaited, got)

- Awaited: Japanese translations should display correctly in the interface.
- Got: Translations worked as expected, and no issues were found.

<img width="886" alt="スクリーンショット 2024-12-01 223448" src="https://github.com/user-attachments/assets/f84cc722-0c52-4801-8379-d2e56dcce5c7">

2024-12-04 13:45 UTC, MAGICCC requested changes

2024-12-04 13:45 UTC, MAGICCC commented on data/web/inc/vars.inc.php
> +  'ja-jp' => '日本語 (Japanese)',
Maybe we should move that up to Italian

2024-12-04 21:05 UTC, kotaroman commented on data/web/inc/vars.inc.php
> +  'ja-jp' => '日本語 (Japanese)',
@MAGICCC 
Thank you for the suggestion! I have already updated the code to move Japanese (日本語) below Italian (Italiano). Please let me know if there are any further adjustments needed.

2024-12-04 21:05 UTC, kotaroman commented
I have updated the PR to move Japanese (日本語) below Italian (Italiano) as suggested. Let me know if there are any other changes required.

2024-12-05 16:47 UTC, MAGICCC approved these changes

2024-12-05 16:48 UTC, MAGICCC commented
@DerLinkman 
Looks ok, need to check how to integrate it into weblate once merged, prob only need to add the language inside weblate

2024-12-06 08:44 UTC, merged

2024-12-06 08:44 UTC, DerLinkman commented
Thank you! Greetings to Japan :)

2024-12-06 23:36 UTC, kotaroman commented
Thank you for merging the PR! I'm glad to contribute. I hope Mailcow will continue to grow! 😊
@DerLinkman @MAGICCC